// Generated by tools/build_sw.py. Do not edit.
'use strict';

const VERSION = "837b131190aa";
const CACHE = 'takedown-' + VERSION;
const FONTS = 'takedown-fonts';
const FILES = [
  "assets/apple-touch-icon.png",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/icon-maskable-512.png",
  "assets/sprites/apocalypse.png",
  "assets/sprites/batman.png",
  "assets/sprites/catwoman.png",
  "assets/sprites/clayface.png",
  "assets/sprites/feilong.png",
  "assets/sprites/joker.png",
  "assets/sprites/juggernaut.png",
  "assets/sprites/komaku.png",
  "assets/sprites/penguin.png",
  "assets/sprites/ryu.png",
  "assets/sprites/sagat.png",
  "assets/sprites/scarecrow.png",
  "assets/sprites/superman.png",
  "assets/sprites/thawk.png",
  "assets/sprites/toki.png",
  "assets/sprites/wolverine.png",
  "assets/sprites/zangief.png",
  "assets/stages/cafe.png",
  "assets/stages/funhouse.png",
  "assets/stages/gotham.png",
  "assets/voice/apocalypse.mp3",
  "assets/voice/bang_gun.mp3",
  "assets/voice/batarang.mp3",
  "assets/voice/batman.mp3",
  "assets/voice/berserker_barrage.mp3",
  "assets/voice/bird_copter.mp3",
  "assets/voice/cat_pounce.mp3",
  "assets/voice/catwoman.mp3",
  "assets/voice/clay_brick.mp3",
  "assets/voice/clayface.mp3",
  "assets/voice/draw.mp3",
  "assets/voice/drill_arm.mp3",
  "assets/voice/fear_gas_gun.mp3",
  "assets/voice/fei_long.mp3",
  "assets/voice/fight.mp3",
  "assets/voice/final_round.mp3",
  "assets/voice/flying_fist.mp3",
  "assets/voice/grapple_strike.mp3",
  "assets/voice/hadouken.mp3",
  "assets/voice/heat_vision.mp3",
  "assets/voice/heavenly_leap.mp3",
  "assets/voice/hokuto_dash.mp3",
  "assets/voice/joker.mp3",
  "assets/voice/joker_bomb.mp3",
  "assets/voice/juggernaut.mp3",
  "assets/voice/juggernaut_charge.mp3",
  "assets/voice/knockout.mp3",
  "assets/voice/komaku.mp3",
  "assets/voice/mud_ball.mp3",
  "assets/voice/penguin.mp3",
  "assets/voice/perfect.mp3",
  "assets/voice/pole_strike.mp3",
  "assets/voice/rekka_ken.mp3",
  "assets/voice/rising_hawk.mp3",
  "assets/voice/round_one.mp3",
  "assets/voice/round_two.mp3",
  "assets/voice/ryu.mp3",
  "assets/voice/sagat.mp3",
  "assets/voice/scarecrow.mp3",
  "assets/voice/shien_kyaku.mp3",
  "assets/voice/shoryuken.mp3",
  "assets/voice/spike_burst.mp3",
  "assets/voice/spinning_lariat.mp3",
  "assets/voice/spinning_piledriver.mp3",
  "assets/voice/storm_hammer.mp3",
  "assets/voice/superman.mp3",
  "assets/voice/t_hawk.mp3",
  "assets/voice/terror_claws.mp3",
  "assets/voice/tiger_shot.mp3",
  "assets/voice/tiger_uppercut.mp3",
  "assets/voice/time_over.mp3",
  "assets/voice/toki.mp3",
  "assets/voice/tornado_claw.mp3",
  "assets/voice/umbrella_gun.mp3",
  "assets/voice/unstoppable.mp3",
  "assets/voice/versus.mp3",
  "assets/voice/whip_lash.mp3",
  "assets/voice/wind_claw.mp3",
  "assets/voice/wins.mp3",
  "assets/voice/wolverine.mp3",
  "assets/voice/zangief.mp3",
  "css/style.css",
  "index.html",
  "js/ai.js",
  "js/audio.js",
  "js/effects.js",
  "js/fighter.js",
  "js/game.js",
  "js/input.js",
  "js/main.js",
  "js/moves.js",
  "js/sprite-data.js",
  "js/sprites.js",
  "js/stage.js",
  "js/util.js",
  "js/voice-data.js",
  "manifest.webmanifest"
];

// Download the whole game in the background; a new version waits in its own cache
// until it is complete, so a half-updated game is never served. cache: 'reload'
// skips the browser's HTTP cache, which may still hold the previous build's files.
self.addEventListener('install', (e) => {
  e.waitUntil(
    caches
      .open(CACHE)
      .then((c) => c.addAll(['./', ...FILES].map((u) => new Request(u, { cache: 'reload' }))))
      .then(() => self.skipWaiting())
  );
});

// Drop caches from older versions.
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== FONTS).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Google Fonts: serve the saved copy, refresh it in the background.
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(
      caches.open(FONTS).then((c) =>
        c.match(req).then((hit) => {
          const net = fetch(req)
            .then((res) => {
              if (res.ok || res.type === 'opaque') c.put(req, res.clone());
              return res;
            })
            .catch(() => hit);
          return hit || net;
        })
      )
    );
    return;
  }

  if (url.origin !== self.location.origin || url.pathname.startsWith('/_vercel/')) return;

  // The game itself: straight from this version's cache, network only for anything
  // not in it. Pages always resolve to the cached index.html.
  e.respondWith(
    caches.open(CACHE).then((c) =>
      c.match(req.mode === 'navigate' ? './' : req, { ignoreSearch: true }).then((hit) => hit || fetch(req))
    )
  );
});
