#!/usr/bin/env python3
"""
Announcer voice builder for Take Down.

Renders every announcer line (round calls, FIGHT, KNOCKOUT, fighter names, super
names) with the Piper neural TTS, gives it an arcade-announcer treatment with ffmpeg
(deeper, compressed, a short arena echo) and writes assets/voice/<key>.mp3 plus
js/voice-data.js listing the clips.

  uv run --no-project --with piper-tts python tools/build_voice.py <voice.onnx> [--missing]

--missing renders only lines that have no clip yet, leaving existing clips untouched.

Voice model: https://huggingface.co/rhasspy/piper-voices (en_US/hfc_male/medium used:
clearest of five voices when transcribed back with Whisper).
Needs ffmpeg with libmp3lame.
"""
import json
import os
import re
import subprocess
import sys
import tempfile
import wave

from piper import PiperVoice
from piper.config import SynthesisConfig

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG = os.path.join(ROOT, 'tools', 'characters.json')
OUT_DIR = os.path.join(ROOT, 'assets', 'voice')
OUT_JS = os.path.join(ROOT, 'js', 'voice-data.js')

# key -> (text spoken, speed: higher = slower)
FIXED = {
    'round_one': ('Round one!', 1.15),
    'round_two': ('Round two!', 1.15),
    'final_round': ('Final round!', 1.2),
    'fight': ('Fight!', 0.9),
    'knockout': ('Knockout!', 1.25),
    'versus': ('versus', 1.1),
    'wins': ('wins!', 1.1),
    'time_over': ('Time over!', 1.2),
    'draw': ('Draw!', 1.1),
    'perfect': ('Perfect!', 1.15),
}

# Spellings (and optional speed) that read better aloud than the on-screen names; each was
# checked by transcribing the clip back with Whisper.
SAY_AS = {
    'T. HAWK': 'Tee Hawk', 'FEI LONG': 'Fay Long', 'BANG! GUN': 'Bang gun',
    'RYU': 'Ree you', 'SAGAT': 'Sah gat', 'ZANGIEF': 'Zang eef', 'TOKI': 'Toe key',
    'KOMAKU': 'Koh mah koo', 'CLAYFACE': 'Clay. Face', 'JUGGERNAUT': ('Jugger-not', 1.15),
    'HADOUKEN': 'Hah doe ken', 'SHORYUKEN': 'Show ree you ken', 'REKKA KEN': 'Wreck ah ken',
    'SHIEN KYAKU': 'Shee en kyah koo', 'HOKUTO DASH': 'Hokuto dash', 'BATARANG': 'Bat-a-rang',
    'JUGGERNAUT CHARGE': ('Jugger-not. Charge', 1.1), 'HEAT VISION': 'Heat. Vision',
    'POLE STRIKE': 'Poll strike', 'WHIP LASH': 'Whip. Lash', 'TERROR CLAWS': 'Terror. Claws',
    'CLAY BRICK': ('Clay. Brick', 1.15),
}

# deeper (-3 semitones-ish at the same speed), warm, punchy, short slap-back echo
FX = ('asetrate=22050*0.86,aresample=44100,atempo=1/0.86,'
      'highpass=f=70,equalizer=f=140:t=q:w=1:g=5,equalizer=f=3200:t=q:w=1.2:g=3,'
      'acompressor=threshold=-20dB:ratio=5:attack=4:release=120:makeup=4,'
      'aecho=0.8:0.55:70|140:0.28|0.14,'
      'silenceremove=start_periods=1:start_threshold=-45dB,'
      'apad=pad_dur=0.05')


def peak_db(path):
    out = subprocess.run(['ffmpeg', '-hide_banner', '-i', path, '-af', 'volumedetect', '-f', 'null', '-'],
                         capture_output=True, text=True).stderr
    return float(re.search(r'max_volume: (-?[\d.]+) dB', out).group(1))


def key_for(text):
    return re.sub(r'[^a-z0-9]+', '_', text.lower()).strip('_')


def lines():
    cfg = json.load(open(CONFIG))['characters']
    out = dict(FIXED)
    for c in cfg.values():
        for n in [c['name']] + [c[s]['name'] for s in ('super1', 'super2') if c.get(s) and c[s].get('name')]:
            text, speed = SAY_AS.get(n, n.title()), 1.0
            if isinstance(text, tuple):  # (spelling, speed)
                text, speed = text
            out.setdefault(key_for(n), (text + ('!' if n != c['name'] else ''), speed))
    return out


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    voice = PiperVoice.load(sys.argv[1])
    os.makedirs(OUT_DIR, exist_ok=True)
    todo = lines()
    only_missing = '--missing' in sys.argv
    with tempfile.TemporaryDirectory() as tmp:
        for key, (text, speed) in todo.items():
            if only_missing and os.path.exists(os.path.join(OUT_DIR, key + '.mp3')):
                continue
            raw = os.path.join(tmp, key + '.wav')
            with wave.open(raw, 'wb') as w:
                voice.synthesize_wav(text, w, syn_config=SynthesisConfig(length_scale=speed))
            fx = os.path.join(tmp, key + '.fx.wav')
            subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', raw, '-af', FX, '-ac', '1', fx], check=True)
            # second pass: every clip peaks at the same level (loudnorm is unreliable on clips this short)
            gain = -1.0 - peak_db(fx)
            subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', fx, '-af', f'volume={gain:.2f}dB',
                            '-c:a', 'libmp3lame', '-b:a', '64k', os.path.join(OUT_DIR, key + '.mp3')], check=True)
            print(key, '<-', text)
    with open(OUT_JS, 'w') as f:
        f.write('// Generated by tools/build_voice.py. Do not edit.\n\'use strict\';\n\n')
        f.write('const VOICE_CLIPS = ' + json.dumps(sorted(todo)) + ';\n')
    print(len(todo), 'clips ->', OUT_DIR)


if __name__ == '__main__':
    main()
