#!/usr/bin/env python3
"""
Service worker builder for Take Down.

Writes sw.js: a precache list of every file the game ships (page, code, sprites,
stages, announcer clips, icons) and a VERSION that is a hash of all of them. The
browser re-checks sw.js on every visit; when any shipped file changed, the hash
changes, the new worker downloads the new set in the background and takes over on
the next visit. Unchanged deploys keep the same cache, so repeat visits load
everything from disk and the game plays offline.

Run before every deploy (tools/deploy.sh does it):

  python3 tools/build_sw.py
"""
import hashlib
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHIP = ['index.html', 'manifest.webmanifest', 'css', 'js', 'assets']
SKIP = {'assets/og.png'}  # only link previews fetch it


def shipped():
    out = []
    for top in SHIP:
        path = os.path.join(ROOT, top)
        if os.path.isfile(path):
            out.append(top)
            continue
        for d, _, files in os.walk(path):
            for f in files:
                rel = os.path.relpath(os.path.join(d, f), ROOT).replace(os.sep, '/')
                if rel not in SKIP and not f.startswith('.'):
                    out.append(rel)
    return sorted(out)


TEMPLATE = """// Generated by tools/build_sw.py. Do not edit.
'use strict';

const VERSION = %(version)s;
const CACHE = 'takedown-' + VERSION;
const FONTS = 'takedown-fonts';
const FILES = %(files)s;

// Download the whole game in the background; a new version waits in its own cache
// until it is complete, so a half-updated game is never served. cache: 'reload'
// skips the browser's HTTP cache, which may still hold the previous build's files.
self.addEventListener('install', (e) => {
  e.waitUntil(
    caches
      .open(CACHE)
      .then((c) => c.addAll(['./', ...FILES].map((u) => new Request(u, { cache: 'reload' }))))
      .then(() => self.skipWaiting())
  );
});

// Drop caches from older versions.
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== FONTS).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Google Fonts: serve the saved copy, refresh it in the background.
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(
      caches.open(FONTS).then((c) =>
        c.match(req).then((hit) => {
          const net = fetch(req)
            .then((res) => {
              if (res.ok || res.type === 'opaque') c.put(req, res.clone());
              return res;
            })
            .catch(() => hit);
          return hit || net;
        })
      )
    );
    return;
  }

  if (url.origin !== self.location.origin || url.pathname.startsWith('/_vercel/')) return;

  // The game itself: straight from this version's cache, network only for anything
  // not in it. Pages always resolve to the cached index.html.
  e.respondWith(
    caches.open(CACHE).then((c) =>
      c.match(req.mode === 'navigate' ? './' : req, { ignoreSearch: true }).then((hit) => hit || fetch(req))
    )
  );
});
"""


def main():
    files = shipped()
    h = hashlib.sha256()
    for rel in files:
        h.update(rel.encode())
        with open(os.path.join(ROOT, rel), 'rb') as f:
            h.update(f.read())
    version = h.hexdigest()[:12]
    with open(os.path.join(ROOT, 'sw.js'), 'w') as f:
        f.write(TEMPLATE % {'version': json.dumps(version), 'files': json.dumps(files, indent=2)})
    size = sum(os.path.getsize(os.path.join(ROOT, r)) for r in files)
    print(f'sw.js: version {version}, {len(files)} files, {size / 1e6:.2f} MB precached')


if __name__ == '__main__':
    main()
